### ISSUE TITLE
Tutorial/demo script for `grep`

### ISSUE THREAD

**Issue by veracioux** [veracioux/tuterm-collection#6]
Create a tuterm script for the `grep` command. The main script should cover the basics (we can decide on those on the fly). We can make additional scripts that cover advanced usage. We can even create a detailed script that acts as a tutorial for regex. All of this does not have to be implemented in a single PR.

**Comment by davidalami** [comment]
Hello @veracioux !  I would like to implement the script. However, we need some sample text files. The first thing I was thinking about is to use system logs, however different users have different logs, leading to unreproducible results. How should we handle it? I suggest to create a `resources` folder with sample text files. What do you think?

**Comment by veracioux** [comment]
Hi @davidalami. Thanks for offering your help. Yes, we should always make the tutorials reproducible and therefore use our own sample files. In fact, I am going to make a small contribution guide that mandates this.

I suggest you first create a list of commands that you want to showcase, and then create the files to fit those needs. Btw, you can use `cheat` and `tldr` commands for inspiration when judging which commands are most important.

I also intend to integrate tuterm with those two projects some day, so that a tuterm script can be used to generate tldr and cheat sheets, or vice versa.

**Comment by davidalami** [comment]
Thank you for suggestions, `cheat` and `tldr` seem very useful. Okay, I think the best way is to create files "on the fly" and remove them after script exits. Getting down to work!
